//! The `docs` form: a Starlight site added to a repository that has none.
//!
//! The first form that adds to someone else's tree instead of starting its
//! own. Everything it writes lives under `docs/`, plus the one workflow that
//! publishes it, and it writes nothing that is already there: a repository
//! generated by lyrn already has `docs/adr/`, and the site lands beside it.
//!
//! Beyond the site, the build writes the same documentation in the form an
//! agent reads (`llms.txt`, `llms-full.txt` and a Markdown twin of every page)
//! and checks that the site agrees with itself about its own address. Both are
//! Astro integrations inside the generated project, so they run on every build
//! rather than once, here.

use crate::generate::{Contents, SourceFile};

/// The manifest text shipped with this form.
pub const MANIFEST: &str = include_str!("docs/template.toml");

/// Files that say a repository already has a documentation site. A second
/// site beside one of these would be two truths about the same product, so
/// the form refuses rather than adding it.
pub const FOREIGN_SITES: &[&str] = &[
    "docs/astro.config.mjs",
    "docs/astro.config.ts",
    "docs/book.toml",
    "book.toml",
    "docs/mkdocs.yml",
    "mkdocs.yml",
    "docs/conf.py",
    "docs/_config.yml",
    "docs/docusaurus.config.js",
    "docs/docusaurus.config.ts",
    "docs/.vitepress/config.ts",
    "docs/.vitepress/config.mjs",
];

fn text(path: &'static str, contents: &'static str) -> SourceFile {
    SourceFile {
        path,
        contents: Contents::Text(contents),
        executable: false,
        addon: None,
    }
}

/// Every file the `docs` form writes, relative to the repository's root.
pub fn sources() -> Vec<SourceFile> {
    vec![
        text("docs/package.json", include_str!("docs/package.json.tmpl")),
        text("docs/pnpm-workspace.yaml", include_str!("docs/pnpm-workspace.yaml.tmpl")),
        text("docs/.gitignore", include_str!("docs/gitignore.tmpl")),
        text("docs/tsconfig.json", include_str!("docs/tsconfig.json.tmpl")),
        text("docs/astro.config.mjs", include_str!("docs/astro.config.mjs.tmpl")),
        text("docs/src/content.config.ts", include_str!("docs/content.config.ts.tmpl")),
        text("docs/src/content/i18n/en.json", include_str!("docs/i18n-en.json.tmpl")),
        text("docs/src/content/docs/index.md", include_str!("docs/content/index.md.tmpl")),
        text("docs/src/content/docs/404.md", include_str!("docs/content/404.md.tmpl")),
        text("docs/src/content/docs/getting-started.md", include_str!("docs/content/getting-started.md.tmpl")),
        text(
            "docs/src/content/docs/guides/writing-a-page.md",
            include_str!("docs/content/guides/writing-a-page.md.tmpl"),
        ),
        text("docs/src/content/docs/reference/site.md", include_str!("docs/content/reference/site.md.tmpl")),
        text("docs/src/integrations/address.mjs", include_str!("docs/integrations/address.mjs")),
        text("docs/src/integrations/llms.mjs", include_str!("docs/integrations/llms.mjs")),
        text("docs/src/styles/brand.css", include_str!("docs/brand.css.tmpl")),
        text("docs/src/assets/logo.svg", include_str!("docs/logo.svg.tmpl")),
        text("docs/public/favicon.svg", include_str!("docs/logo.svg.tmpl")),
        text(".github/workflows/docs.yml", include_str!("docs/github/docs.yml.tmpl")),
    ]
}
