//! The `docs` form: a Starlight site added to a repository that has none.
//!
//! The first form that adds to someone else's tree instead of starting its
//! own. Everything it writes lives under `docs/`, plus the workflow that
//! publishes it and the one that audits its packages, and it writes nothing
//! that is already there: a repository generated by lyrn already has
//! `docs/adr/`, and the site lands beside it.
//!
//! Beyond the site, the build writes the same documentation in the form an
//! agent reads (`llms.txt`, `llms-full.txt` and a Markdown twin of every page)
//! and checks that the site agrees with itself about its own address. Both are
//! Astro integrations inside the generated project, so they run on every build
//! rather than once, here.

use crate::generate::{Contents, SourceFile};

/// The manifest text shipped with this form.
pub const MANIFEST: &str = include_str!("docs/template.toml");

/// Files that say a repository already has a documentation site. A second
/// site beside one of these would be two truths about the same product, so
/// the form refuses rather than adding it.
pub const FOREIGN_SITES: &[&str] = &[
    "docs/astro.config.mjs",
    "docs/astro.config.ts",
    "docs/book.toml",
    "book.toml",
    "docs/mkdocs.yml",
    "mkdocs.yml",
    "docs/conf.py",
    "docs/_config.yml",
    "docs/docusaurus.config.js",
    "docs/docusaurus.config.ts",
    "docs/.vitepress/config.ts",
    "docs/.vitepress/config.mjs",
];

fn text(path: &'static str, contents: &'static str) -> SourceFile {
    SourceFile {
        path,
        contents: Contents::Text(contents),
        executable: false,
        addon: None,
    }
}

/// Every file the `docs` form writes, relative to the repository's root.
pub fn sources() -> Vec<SourceFile> {
    vec![
        text("docs/package.json", include_str!("docs/package.json.tmpl")),
        text("docs/pnpm-workspace.yaml", include_str!("docs/pnpm-workspace.yaml.tmpl")),
        text("docs/.gitignore", include_str!("docs/gitignore.tmpl")),
        text("docs/tsconfig.json", include_str!("docs/tsconfig.json.tmpl")),
        text("docs/astro.config.mjs", include_str!("docs/astro.config.mjs.tmpl")),
        text("docs/src/content.config.ts", include_str!("docs/content.config.ts.tmpl")),
        text("docs/src/content/i18n/en.json", include_str!("docs/i18n-en.json.tmpl")),
        text("docs/src/content/docs/index.md", include_str!("docs/content/index.md.tmpl")),
        text("docs/src/content/docs/404.md", include_str!("docs/content/404.md.tmpl")),
        text("docs/src/content/docs/getting-started.md", include_str!("docs/content/getting-started.md.tmpl")),
        text(
            "docs/src/content/docs/guides/writing-a-page.md",
            include_str!("docs/content/guides/writing-a-page.md.tmpl"),
        ),
        text("docs/src/content/docs/reference/site.md", include_str!("docs/content/reference/site.md.tmpl")),
        text("docs/src/integrations/address.mjs", include_str!("docs/integrations/address.mjs")),
        text("docs/src/integrations/llms.mjs", include_str!("docs/integrations/llms.mjs")),
        text("docs/src/styles/brand.css", include_str!("docs/brand.css.tmpl")),
        // The mark, as the exporter lays it out: the header takes level L, the
        // favicon level S, the touch icon L again at 180px. The line's
        // umbrella mark until the product has its own; `pnpm export-assets`
        // redraws all three from the masters in `assets/`.
        text("docs/src/assets/logo.svg", include_str!("dowel/marks/lacodda-L.svg")),
        text("docs/public/favicon.svg", include_str!("dowel/marks/lacodda-S.svg")),
        SourceFile {
            path: "docs/public/apple-touch-icon.png",
            contents: Contents::Binary(include_bytes!("spa/public/apple-touch-icon.png")),
            executable: false,
            addon: None,
        },
        text("docs/export-assets.mjs", include_str!("docs/export-assets.mjs.tmpl")),
        text(".github/workflows/docs.yml", include_str!("docs/github/docs.yml.tmpl")),
        // The site's packages are audited by a workflow of their own: the form adds
        // to a repository and leaves the audit it already runs as it was.
        text(".github/workflows/docs-audit.yml", include_str!("docs/github/docs-audit.yml.tmpl")),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An advisory is accepted with its reason next to it, or not at all: the
    /// audit's whole worth is that a red run means something, and an accepted
    /// advisory nobody can explain is a red run switched off.
    #[test]
    fn every_accepted_advisory_says_why() {
        let settings = include_str!("docs/pnpm-workspace.yaml.tmpl");
        let lines: Vec<&str> = settings.lines().map(str::trim).collect();
        let accepted: Vec<usize> = lines.iter().enumerate().filter(|(_, l)| l.starts_with("- GHSA-")).map(|(i, _)| i).collect();
        assert!(!accepted.is_empty(), "the site accepts no advisory - drop the list rather than leave it empty");
        for at in accepted {
            assert!(lines[at - 1].starts_with('#'), "`{}` is accepted without a reason above it", lines[at]);
        }
    }

    /// The site's audit reads the site's lockfile, from the site's directory -
    /// the repository's own audit knows nothing about `docs/`.
    #[test]
    fn the_site_audit_runs_in_the_site() {
        let workflow = include_str!("docs/github/docs-audit.yml.tmpl");
        assert!(workflow.contains("working-directory: docs"));
        assert!(workflow.contains("cache-dependency-path: docs/pnpm-lock.yaml"));
        assert!(
            workflow.contains(
                "run: pnpm audit
"
            ) || workflow.trim_end().ends_with("run: pnpm audit")
        );
        assert!(!workflow.contains("--prod"), "the site is all build tooling; every package counts");
        let paths: Vec<&str> = sources().iter().map(|s| s.path).collect();
        assert!(paths.contains(&".github/workflows/docs-audit.yml"));
    }
}
