# Changelog

All notable changes to this project are documented here.

The format follows [Conventional Commits](https://www.conventionalcommits.org),
and the file is generated by [git-cliff](https://git-cliff.org) at release time:

```console
$ git cliff --tag v0.1.0 --output CHANGELOG.md
```
