name: documentation

on:
  push:
  pull_request:    

jobs:
  book:
    name: Build and deploy book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-mdbook
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-0.3 }}

      - name: Install mdBook
        run: |
          cargo install mdbook
        env:
          CARGO_HOME: ${{ env.HOME }}/.cargo

      - name: Build Documentation
        run: |
          mdbook build
        working-directory: docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: book